//! Chess notation helpers.
//!
//! The dataset stores moves in UCI (`d1e6`), which is what a program wants and
//! what neither a person nor a language model reads comfortably. Chess
//! literature is written in SAN (`Qxe6+`), so that is what models have seen in
//! training and what a human recognises at a glance.
//!
//! Converting between them is not string manipulation: `Qxe6+` requires
//! knowing which queens could legally reach e6, whether the move gives check,
//! and whether another piece of the same kind needs disambiguating. That is a
//! full rules engine, which is why this module exists and why `shakmaty` is a
//! dependency.

use anyhow::{Context, Result, bail};
use shakmaty::fen::Fen;
use shakmaty::san::SanPlus;
use shakmaty::uci::UciMove;
use shakmaty::{CastlingMode, Chess, Color, EnPassantMode, File, Move, Position, Rank, Square};

/// A puzzle's moves, resolved into every representation the API serves.
#[derive(Debug, Clone)]
pub struct Annotated {
    /// The position the player actually faces, after the opponent's move.
    pub position_fen: String,
    /// The opponent's move in SAN.
    pub initial_move_san: String,
    /// The solution in SAN, aligned with the UCI list.
    pub solution_san: Vec<String>,
    /// The position to solve, drawn for a terminal or a prompt.
    pub board_ascii: String,
    /// Whose turn it is in `position_fen`.
    pub solver_color: Color,
}

fn parse_position(fen: &str) -> Result<Chess> {
    let parsed: Fen = fen
        .parse()
        .map_err(|err| anyhow::anyhow!("{err}"))
        .with_context(|| format!("parsing FEN `{fen}`"))?;
    parsed
        .into_position(CastlingMode::Standard)
        .map_err(|err| anyhow::anyhow!("{err}"))
        .with_context(|| format!("illegal position in `{fen}`"))
}

/// Renders a position as text.
///
/// Language models reason about a drawn board more reliably than about a FEN
/// they have to decode in their head, and it costs a person nothing to read.
/// Coordinates are included because "the knight on f6" is the useful sentence,
/// not "the knight on the sixth row".
pub fn board_ascii(position: &Chess) -> String {
    let board = position.board();
    let mut out = String::with_capacity(200);

    for rank in (0..8).rev() {
        let rank = Rank::new(rank);
        out.push_str(&format!("{} ", rank.char()));
        for file in 0..8 {
            let square = Square::from_coords(File::new(file), rank);
            match board.piece_at(square) {
                Some(piece) => out.push(piece.char()),
                None => out.push('.'),
            }
            out.push(' ');
        }
        out.push('\n');
    }
    out.push_str("  a b c d e f g h");
    out
}

/// Replays a puzzle's moves, producing SAN for each and the position the
/// player is asked to solve.
pub fn annotate(fen: &str, moves: &str) -> Result<Annotated> {
    let mut position = parse_position(fen)?;

    let mut uci_moves = moves.split_whitespace();
    let Some(first) = uci_moves.next() else {
        bail!("puzzle has no moves");
    };

    let initial_move_san = play(&mut position, first)?;
    let solver_color = position.turn();
    let position_fen = Fen::from_position(&position, EnPassantMode::Legal).to_string();
    let board_ascii = board_ascii(&position);

    // The solution is described from the position the player sees, so SAN is
    // generated by replaying it from there.
    let mut replay = position.clone();
    let mut solution_san = Vec::new();
    for uci in uci_moves {
        solution_san.push(play(&mut replay, uci)?);
    }

    Ok(Annotated {
        position_fen,
        initial_move_san,
        solution_san,
        board_ascii,
        solver_color,
    })
}

/// How many pieces, kings included, stand on the board the player solves.
///
/// Rating alone cannot tell a sparse teaching diagram from an easy move
/// buried in a full middlegame, and a beginner has to scan every piece.
pub fn pieces_to_solve(fen: &str, moves: &str) -> Result<u32> {
    let mut position = parse_position(fen)?;
    let Some(first) = moves.split_whitespace().next() else {
        bail!("puzzle has no moves");
    };
    let opponent_move = legal_move(&position, first)?;
    position.play_unchecked(opponent_move);
    Ok(position.board().occupied().count() as u32)
}

fn legal_move(position: &Chess, uci: &str) -> Result<Move> {
    let parsed: UciMove = uci
        .parse()
        .map_err(|err| anyhow::anyhow!("{err}"))
        .with_context(|| format!("parsing UCI move `{uci}`"))?;
    parsed
        .to_move(position)
        .map_err(|err| anyhow::anyhow!("{err}"))
        .with_context(|| format!("`{uci}` is not legal in this position"))
}

fn play(position: &mut Chess, uci: &str) -> Result<String> {
    let legal = legal_move(position, uci)?;
    let san = SanPlus::from_move(position.clone(), legal).to_string();
    position.play_unchecked(legal);
    Ok(san)
}

pub fn color_name(color: Color) -> &'static str {
    match color {
        Color::White => "white",
        Color::Black => "black",
    }
}

/// A link a person can click to see the position on a real board.
pub fn analysis_url(fen: &str) -> String {
    format!("https://lichess.org/analysis/{}", fen.replace(' ', "_"))
}

#[cfg(test)]
mod tests {
    use super::*;

    // Puzzle 00008 from the dataset, whose values are known by hand.
    const FEN: &str = "r6k/pp2r2p/4Rp1Q/3p4/8/1N1P2R1/PqP2bPP/7K b - - 0 24";
    const MOVES: &str = "f2g3 e6e7 b2b1 b3c1 b1c1 h6c1";

    #[test]
    fn converts_uci_to_san() {
        let annotated = annotate(FEN, MOVES).expect("annotates");

        assert_eq!(annotated.initial_move_san, "Bxg3");
        assert_eq!(
            annotated.solution_san,
            ["Rxe7", "Qb1+", "Nc1", "Qxc1+", "Qxc1"],
            "captures, checks and disambiguation all have to come out right"
        );
    }

    #[test]
    fn san_carries_what_uci_cannot() {
        let annotated = annotate(FEN, MOVES).expect("annotates");
        // `b2b1` says nothing about check; `Qb1+` does. That difference is the
        // whole reason for depending on a rules engine.
        assert!(annotated.solution_san[1].ends_with('+'));
        assert!(annotated.solution_san[3].ends_with('+'));
        assert!(
            annotated.solution_san[0].contains('x'),
            "captures are marked"
        );
    }

    #[test]
    fn the_solver_plays_the_colour_opposite_the_fen() {
        let annotated = annotate(FEN, MOVES).expect("annotates");
        // The FEN has black to move; that move belongs to the opponent.
        assert_eq!(color_name(annotated.solver_color), "white");
    }

    #[test]
    fn the_position_advances_past_the_opponents_move() {
        let annotated = annotate(FEN, MOVES).expect("annotates");
        assert_ne!(annotated.position_fen, FEN);
        assert!(
            annotated.position_fen.contains(" w "),
            "after black's move it is white to play, got {}",
            annotated.position_fen
        );
    }

    #[test]
    fn the_board_is_drawn_with_coordinates() {
        let annotated = annotate(FEN, MOVES).expect("annotates");
        let lines: Vec<&str> = annotated.board_ascii.lines().collect();

        assert_eq!(lines.len(), 9, "eight ranks and a file legend");
        assert!(lines[0].starts_with('8'), "rank 8 is drawn first");
        assert!(lines[7].starts_with('1'));
        assert_eq!(lines[8].trim(), "a b c d e f g h");
        // Black king on h8, from the FEN's first field `r6k`.
        assert!(lines[0].trim_end().ends_with('k'));
    }

    #[test]
    fn counts_pieces_after_the_opponents_move() {
        // 20 pieces in the FEN; the opponent's Bxg3 captures a rook.
        assert_eq!(pieces_to_solve(FEN, MOVES).expect("counts"), 19);
    }

    #[test]
    fn rejects_moves_that_are_not_legal() {
        assert!(annotate(FEN, "a1a2 b1b2").is_err());
    }

    #[test]
    fn rejects_a_malformed_fen() {
        assert!(annotate("not a fen", MOVES).is_err());
    }

    #[test]
    fn the_analysis_url_escapes_the_fen() {
        let url = analysis_url("8/8/8/8/8/8/8/K6k w - - 0 1");
        assert_eq!(
            url,
            "https://lichess.org/analysis/8/8/8/8/8/8/8/K6k_w_-_-_0_1"
        );
        assert!(!url.contains(' '), "a URL cannot carry raw spaces");
    }
}
